### ISSUE TITLE
continuous warning in the log

### ISSUE THREAD

**Issue by hadolphs** [mkormendy/homebridge-node-alarm-dot-com#8] opened 2018-10-02 07:13 UTC
Hi,

Thanks for putting this together, its a great improvement from using the old plugin.

Just a quick question, I keep getting this in my homebridge log:

[2018-10-2 03:03:46] [Security system] Warning: Sensor with unknown state 0

Comes over and over again... 

My system doesn't seem to report sensors (I don't see them in my home app, I only see the panel and smoke detector).

Thanks!

**Comment by mkormendy** [comment] 2018-10-02 16:09
Possible duplicate of https://github.com/mkormendy/homebridge-node-alarm-dot-com/issues/4.

**Comment by hadolphs** [comment] 2018-10-02 16:16
Hi @mkormendy , 
Not sure its a duplicate, its probably related though.  I did notice the following as I was going through whats being reported in my alarm.com console... the warning events seem to map to web login events in the console.  I haven't tested disabling that event reporting to see if I stop seeing those warnings in home bridge, but I figured I let you know that could something you should filter out from the log? not sure if you get enough information to not report that event...

**Comment by hadolphs** [comment] 2018-10-02 16:19
> Hi @mkormendy ,
> Not sure its a duplicate, its probably related though. I did notice the following as I was going through whats being reported in my alarm.com console... the warning events seem to map one to one to successful web login events in the console. I haven't tested disabling that event reporting to see if I stop seeing those warnings in home bridge, but I figured I let you know that could something you should filter out from the log? not sure if you get enough information to not report that event...

scratch that - I see a lot more of the warning than this web successful login events in the console... the warnings are coming up about every 2 minutes or less.. while these come every ~10 minutes ... so its probably not that

**Comment by mkormendy** [comment] 2018-10-02 16:37
I'd be interested if your account has full sensor monitoring on it. Check with your provider/Alarm.com.

**Comment by hadolphs** [comment] 2018-10-04 01:48
nope, I only see the smoke detector and the panel.   Also when I open up alarm.com I dont see anything that indicates that I have sensor monitoring enabled...

**Comment by mkormendy** [comment] 2018-10-04 04:35
Well that’s the same problem as issue #4 then.

Contact your provider to find out if you can upgrade.

In the meantime,... I could provide an more specific error log entry to indicate that is the case, with some sort of flag(s) to ignore which device groups that are unsupported due to the user’s alarm account package.

**Comment by mkormendy** [comment] 2018-10-04 16:51
Because it's programmed to do output that warning.

Like I said:

> I could provide an more specific error log entry to indicate that is the case, with some sort of flag(s) to ignore which device groups that are unsupported due to the user’s alarm account package.

**Comment by hadolphs** [comment] 2018-10-04 21:29
Gotcha, now I get it.

Well... yes, maybe you can add a flag in the configuration where you can enable or disable sensor monitoring support.

if its disabled you ignore if its enabled you attempt to use them.  And if you get the error you report that its misconfigured.  I think thats something like what you were describing right?

Thanks!

**Comment by mkormendy** [comment] 2018-12-24 04:04
I have finally updated the plugin to include log level configuration.
Please see the readme for the new additions on how to configure the polling as well as how to change the level of logging to hide the entries in your logs.

**Closed by mkormendy** 2018-12-24 04:04 UTC
Labels: duplicate, enhancement
