### ISSUE TITLE
Unable to trigger any homekit accessories - This callback function has already been called by someone else

### ISSUE THREAD

**Issue by iBanks3** [mkormendy/homebridge-node-alarm-dot-com#43] opened 2020-07-01 12:03 UTC
I am unable to trigger any HomeKit accessories due to the below error. All alarm.com accessories are able to appear in Home app. I have disabled 2FA. Login/Password seems to be accepted as the accessories are being fetched successfully. I have did a complete reinstall of Homebridge and plugin and same error. Any ideas of a next step for me? Thanks

Error:
[7/1/2020, 7:54:51 AM] [Security System] Error: Failed to change light state: Error: POST https://www.alarm.com/web/api/devices/lights/97265971-1211/turnOn failed: 403
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:491:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:918) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/index.js:675:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:918) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by mkormendy** [comment] 2020-07-01 19:38
This seems to be a duplicate of issue #27.

**Closed by mkormendy** 2020-07-01 19:38 UTC
Labels: duplicate, unreproducible, wontfix
